_wandb:
    value:
        cli_version: 0.25.1
        e:
            to9v421ejtyvlko9l94mm75jaro6j6ok:
                args:
                    - --node-ip-address=192.168.179.245
                    - --node-manager-port=33063
                    - --object-store-name=/tmp/ray/ray/session_2026-03-25_19-31-41_638427_458955/sockets/plasma_store
                    - --raylet-name=/tmp/ray/ray/session_2026-03-25_19-31-41_638427_458955/sockets/raylet
                    - --redis-address=None
                    - --metrics-agent-port=60669
                    - --logging-rotate-bytes=536870912
                    - --logging-rotate-backup-count=5
                    - --runtime-env-agent-port=59927
                    - --gcs-address=192.168.179.245:54556
                    - --session-name=session_2026-03-25_19-31-41_638427_458955
                    - --temp-dir=/tmp/ray/ray
                    - --webui=
                    - --cluster-id=908df96e3d65a7d3dd8c5182d9b30615e8bb87c95baca05c2618cc18
                    - --startup-token=130
                    - --worker-launch-time-ms=1774438367629
                    - --node-id=47917e2ace50138a0253dcc37fcac970de9558ccdf847172a001e3d6
                    - --runtime-env-hash=-1092247032
                cpu_count: 320
                cpu_count_logical: 320
                disk:
                    /:
                        total: "1055731638272"
                        used: "127861309440"
                email: leonlee.working@gmail.com
                executable: /sharedata/liyuchen/miniforge3/envs/codescout-npu/bin/python
                git:
                    commit: c7b767750e1b311e775c4b8fcf497ee02d6a5f77
                    remote: https://github.com/yucc-leon/codescout.git
                host: npu-lych-rl-server-6-server-0
                memory:
                    total: "2162447691776"
                os: Linux-5.10.0-182.0.0.95.r1941_123.hce2.aarch64-aarch64-with-glibc2.35
                program: /sharedata/liyuchen/miniforge3/envs/codescout-npu/lib/python3.12/site-packages/ray/_private/workers/default_worker.py
                python: CPython 3.12.13
                root: /sharedata/liyuchen/workspace/codescout
                startedAt: "2026-03-25T11:33:46.332801Z"
                writerId: to9v421ejtyvlko9l94mm75jaro6j6ok
        m: []
        python_version: 3.12.13
        t:
            "1":
                - 1
                - 11
                - 30
                - 49
                - 50
                - 51
                - 71
                - 95
                - 98
                - 105
            "2":
                - 1
                - 11
                - 30
                - 49
                - 50
                - 51
                - 71
                - 95
                - 98
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.13
            "5": 0.25.1
            "6": 4.57.6
            "12": 0.25.1
            "13": linux-aarch64
data:
    value:
        train_data:
            - ./data/swe_smith//train.parquet
        val_data:
            - ./data/swe_smith//validation.parquet
deepspeed_config:
    value:
        eval:
            gradient_clipping: 1
            prescale_gradient: false
            torch_autocast:
                dtype: bfloat16
                enabled: true
            wall_clock_breakdown: false
            zero_optimization:
                offload_param:
                    device: cpu
                    pin_memory: true
                stage: 3
                stage3_param_persistence_threshold: auto
        train:
            data_types:
                grad_accum_dtype: fp32
            disable_trace_cache: false
            gradient_clipping: 1
            prescale_gradient: false
            torch_autocast:
                dtype: bfloat16
                enabled: true
            wall_clock_breakdown: false
            zero_optimization:
                offload_optimizer:
                    device: none
                    pin_memory: true
                offload_param:
                    device: none
                reduce_bucket_size: auto
                round_robin_gradients: true
                stage: 3
                stage3_max_live_parameters: auto
                stage3_max_reuse_distance: auto
                stage3_param_persistence_threshold: auto
                stage3_prefetch_bucket_size: auto
                sub_group_size: auto
                zero_hpz_partition_size: 1
                zero_quantized_gradients: false
                zero_quantized_weights: false
environment:
    value:
        env_class: gsm8k
        skyrl_gym:
            llm_as_a_judge:
                base_url: null
                model: gpt-4o-mini
            max_env_workers: 32
            search:
                log_requests: false
                search_url: http://127.0.0.1:8000/retrieve
                timeout: 30
                topk: 3
            text2sql:
                db_path: /home/ray/default/sql_data
generator:
    value:
        append_eos_token_after_stop_str_in_multi_turn: true
        apply_overlong_filtering: false
        async_engine: true
        backend: vllm
        batched: false
        chat_template:
            name_or_path: null
            source: name
        enable_chunked_prefill: true
        enable_http_endpoint: true
        enable_prefix_caching: true
        enforce_eager: true
        engine_init_kwargs:
            disable_cascade_attn: true
            enable_auto_tool_choice: true
            max_model_len: 32768
            tool_call_parser: hermes
        eval_n_samples_per_prompt: 1
        eval_sampling_params:
            logprobs: null
            max_generate_length: 8192
            min_p: 0
            repetition_penalty: 1
            stop: null
            temperature: 0
            top_k: -1
            top_p: 1
        fully_sharded_loras: false
        gpu_memory_utilization: 0.7
        http_endpoint_host: 0.0.0.0
        http_endpoint_port: 8080
        inference_engine_data_parallel_size: 1
        inference_engine_expert_parallel_size: 1
        inference_engine_pipeline_parallel_size: 1
        inference_engine_tensor_parallel_size: 1
        max_input_length: 32768
        max_num_batched_tokens: 65536
        max_num_seqs: 1024
        max_turns: 6
        model_dtype: bfloat16
        model_name: /sharedata/liyuchen/models/Qwen3-4B-Instruct-2507
        n_samples_per_prompt: 4
        num_inference_engines: 4
        override_existing_update_group: disable
        prompts:
            system_prompt: templates/system_prompt_custom_finish.j2
            user_prompt: templates/file_module_custom_finish.j2
        remote_inference_engine_urls:
            - 127.0.0.1:8001
        reward:
            - fn: multilevel_localization_f1_reward
        rope_scaling: null
        rope_theta: null
        run_engines_locally: true
        sampling_params:
            logprobs: null
            max_generate_length: 8192
            min_p: 0
            repetition_penalty: 1
            stop: null
            temperature: 1
            top_k: -1
            top_p: 1
        tools:
            - terminal
        traj_dir: /tmp/codescout_ckpts/trajectories/
        use_conversation_multi_turn: true
        vllm_v1_disable_multiproc: true
        weight_sync_backend: nccl
        weight_transfer_threshold_cuda_ipc_GB: 1
        zero_reward_on_non_stop: false
run_async_trainer:
    value: true
trainer:
    value:
        algorithm:
            advantage_batch_normalize: false
            advantage_estimator: grpo
            cispo:
                cispo_eps_clip_high: 5
                cispo_eps_clip_low: 0
            clip_cov:
                clip_cov_lb: 1
                clip_cov_ub: 5
                clip_ratio: 0.0002
            clip_ratio_c: 3
            dynamic_sampling:
                max_sample_batches: 30
                min_replace_ratio: 0.3
                type: null
            entropy_loss_coef: 0.01
            eps_clip_high: 0.0004
            eps_clip_low: 0.0003
            gamma: 1
            grpo_norm_by_std: false
            kl_cov:
                kl_cov_frac: 0.2
                ppo_kl_coef: 1
            kl_ctrl:
                horizon: 10000
                kl_target: 0.1
                type: fixed
            kl_estimator_type: k3
            kl_loss_coef: 0.001
            lambd: 1
            loss_reduction: sequence_mean
            max_seq_len: 40960
            policy_loss_type: gspo
            tis_imp_ratio_cap: -1
            use_abs_kl: false
            use_entropy_loss: false
            use_kl_estimator_k3: false
            use_kl_in_reward: false
            use_kl_loss: false
            use_tis: false
            value_clip: 0.2
            value_head_prefix: value_head
        bf16: true
        ckpt_interval: 10
        ckpt_path: /tmp/codescout_ckpts
        critic:
            deepspeed_config:
                data_types:
                    grad_accum_dtype: fp32
                disable_trace_cache: false
                gradient_clipping: 1
                prescale_gradient: false
                torch_autocast:
                    dtype: bfloat16
                    enabled: true
                wall_clock_breakdown: false
                zero_optimization:
                    offload_optimizer:
                        device: none
                        pin_memory: true
                    offload_param:
                        device: none
                    reduce_bucket_size: auto
                    round_robin_gradients: true
                    stage: 3
                    stage3_max_live_parameters: auto
                    stage3_max_reuse_distance: auto
                    stage3_param_persistence_threshold: auto
                    stage3_prefetch_bucket_size: auto
                    sub_group_size: auto
                    zero_hpz_partition_size: 1
                    zero_quantized_gradients: false
                    zero_quantized_weights: false
            fsdp_config:
                cpu_offload: false
                fsdp_size: -1
                reshard_after_forward: true
            model:
                lora:
                    alpha: 16
                    dropout: 0
                    rank: 0
                path: null
            optimizer_config:
                adam_betas:
                    - 0.9
                    - 0.999
                lr: 5e-06
                max_grad_norm: 1
                num_warmup_steps: 0
                offload_after_step: true
                scheduler: constant_with_warmup
                weight_decay: 0.01
            sequence_parallel_size: 1
        critic_mini_batch_size: 256
        disable_fast_tokenizer: false
        dump_data_batch: true
        dump_eval_results: true
        epochs: 1
        eval_batch_size: 10
        eval_before_train: false
        eval_interval: -1
        exclude_modules: null
        export_path: /tmp/codescout_ckpts/exported_model/
        flash_attn: false
        fully_async:
            max_staleness_steps: 4
            num_parallel_generation_workers: 4
        gradient_checkpointing: true
        gradient_checkpointing_use_reentrant: false
        hf_save_interval: 50
        logger: wandb
        max_ckpts_to_keep: 5
        max_prompt_length: 32768
        micro_forward_batch_size_per_gpu: 1
        micro_train_batch_size_per_gpu: 1
        placement:
            colocate_all: false
            colocate_policy_ref: true
            critic_num_gpus_per_node: 4
            critic_num_nodes: 1
            policy_num_gpus_per_node: 4
            policy_num_nodes: 1
            ref_num_gpus_per_node: 4
            ref_num_nodes: 1
        policy:
            deepspeed_config:
                data_types:
                    grad_accum_dtype: fp32
                disable_trace_cache: false
                gradient_clipping: 1
                prescale_gradient: false
                torch_autocast:
                    dtype: bfloat16
                    enabled: true
                wall_clock_breakdown: false
                zero_optimization:
                    offload_optimizer:
                        device: none
                        pin_memory: true
                    offload_param:
                        device: none
                    reduce_bucket_size: auto
                    round_robin_gradients: true
                    stage: 3
                    stage3_max_live_parameters: auto
                    stage3_max_reuse_distance: auto
                    stage3_param_persistence_threshold: auto
                    stage3_prefetch_bucket_size: auto
                    sub_group_size: auto
                    zero_hpz_partition_size: 1
                    zero_quantized_gradients: false
                    zero_quantized_weights: false
            fsdp_config:
                cpu_offload: true
                fsdp_size: -1
                reshard_after_forward: true
            megatron_config:
                context_parallel_size: 1
                ddp_config:
                    average_in_collective: true
                    grad_reduce_in_fp32: true
                    overlap_grad_reduce: false
                    overlap_param_gather: false
                expert_model_parallel_size: 1
                expert_tensor_parallel_size: null
                optimizer_config_kwargs:
                    optimizer_cpu_offload: false
                    optimizer_offload_fraction: 0
                    overlap_cpu_optimizer_d2h_h2d: false
                    use_precision_aware_optimizer: false
                pipeline_model_parallel_size: 1
                tensor_model_parallel_size: 1
                torch_profiler_config:
                    enable: false
                    ranks: []
                    save_path: null
                transformer_config_kwargs:
                    recompute_granularity: null
                    recompute_method: null
                    recompute_modules:
                        - core_attn
                    recompute_num_layers: null
            model:
                lora:
                    alpha: 16
                    dropout: 0
                    lora_sync_path: /tmp/skyrl_lora_sync
                    rank: 0
                path: /sharedata/liyuchen/models/Qwen3-4B-Instruct-2507
            optimizer_config:
                adam_betas:
                    - 0.9
                    - 0.999
                lr: 1e-06
                max_grad_norm: 1
                num_warmup_steps: 0
                offload_after_step: true
                scheduler: constant_with_warmup
                weight_decay: 0.01
            record_memory: false
            sequence_parallel_size: 1
            use_torch_compile: false
        policy_mini_batch_size: 4
        project_name: code_search_npu
        ref:
            deepspeed_config:
                gradient_clipping: 1
                prescale_gradient: false
                torch_autocast:
                    dtype: bfloat16
                    enabled: true
                wall_clock_breakdown: false
                zero_optimization:
                    offload_param:
                        device: cpu
                        pin_memory: true
                    stage: 3
                    stage3_param_persistence_threshold: auto
            fsdp_config:
                cpu_offload: false
                fsdp_size: -1
                reshard_after_forward: true
            megatron_config:
                context_parallel_size: 1
                expert_model_parallel_size: 1
                expert_tensor_parallel_size: 1
                pipeline_model_parallel_size: 1
                tensor_model_parallel_size: 1
            model:
                path: /sharedata/liyuchen/models/Qwen3-4B-Instruct-2507
            sequence_parallel_size: 1
        resume_mode: none
        resume_path: null
        rope_scaling: null
        rope_theta: null
        run_name: Qwen3-4B-Instruct-2507-npu-4x4
        seed: 42
        sequence_parallel_backend: ulysses
        step_wise_training: false
        strategy: fsdp2
        target_modules: all-linear
        train_batch_size: 4
        update_epochs_per_batch: 1
        update_ref_every_epoch: false
        use_sample_packing: false
